### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by reiz**
Add dependency badge and reference badge. All dependencies are up-to-date. Keep up the good work.

### CODE REVIEW

**Comment by Rarst** [comment]
Sorry, I am not big fan of badges overall and don't see the point in these metrics for this project.

**Comment by reiz** [comment]
@Rarst totally respect that. 

Badges show very quickly the status of a project. I like them and many others as well. But if you don't, that's fine :-)

**Comment by reiz** [comment]
@Rarst By the way, even if you don't like badges, a README.md file with some kind of basic documentation would be cool ;-)

**Comment by Rarst** [comment]
I know, this theme is pretty much internal project open sourced for the sake of why–not and some technical demos. :) It will make to a point of needing and getting proper documentation eventually, but not at the moment.

**Pull request closed without merging**
